/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfirmedRouteImport } from './routes/confirmed'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as Dash2RouteImport } from './routes/dash2'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AreasIndexRouteImport } from './routes/areas/index'
import { Route as AreasSlugRouteImport } from './routes/areas/$slug'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as Blog24HourPunctureRepairLondonRouteImport } from './routes/blog/24-hour-puncture-repair-london'
import { Route as BlogAllSeasonVsWinterTyresUkRouteImport } from './routes/blog/all-season-vs-winter-tyres-uk'
import { Route as BlogBudgetVsPremiumTyresUkRouteImport } from './routes/blog/budget-vs-premium-tyres-uk'
import { Route as BlogCanAPunctureBeRepairedUkRouteImport } from './routes/blog/can-a-puncture-be-repaired-uk'
import { Route as BlogCanIDriveOnAFlatTyreUkRouteImport } from './routes/blog/can-i-drive-on-a-flat-tyre-uk'
import { Route as BlogCrackedAlloyFromPotholeRouteImport } from './routes/blog/cracked-alloy-from-pothole'
import { Route as BlogEmergencyPunctureRepairLondonRouteImport } from './routes/blog/emergency-puncture-repair-london'
import { Route as BlogFlatTyreLondonRouteImport } from './routes/blog/flat-tyre-london'
import { Route as BlogLockingWheelNutLostUkRouteImport } from './routes/blog/locking-wheel-nut-lost-uk'
import { Route as BlogMobilePunctureRepairLondonRouteImport } from './routes/blog/mobile-puncture-repair-london'
import { Route as BlogMobileTyreFitterM25RouteImport } from './routes/blog/mobile-tyre-fitter-m25'
import { Route as BlogMobileTyreFitterVsGarageRouteImport } from './routes/blog/mobile-tyre-fitter-vs-garage'
import { Route as BlogMobileTyreFittingBirminghamRouteImport } from './routes/blog/mobile-tyre-fitting-birmingham'
import { Route as BlogMobileTyreFittingLondonRouteImport } from './routes/blog/mobile-tyre-fitting-london'
import { Route as BlogMobileTyreFittingManchesterRouteImport } from './routes/blog/mobile-tyre-fitting-manchester'
import { Route as BlogNailInTyreWhatToDoRouteImport } from './routes/blog/nail-in-tyre-what-to-do'
import { Route as BlogPotholeDamageClaimUkRouteImport } from './routes/blog/pothole-damage-claim-uk'
import { Route as BlogPunctureRepairCentralLondonRouteImport } from './routes/blog/puncture-repair-central-london'
import { Route as BlogPunctureRepairCostUkRouteImport } from './routes/blog/puncture-repair-cost-uk'
import { Route as BlogPunctureRepairVsNewTyreRouteImport } from './routes/blog/puncture-repair-vs-new-tyre'
import { Route as BlogRoadsidePunctureRepairLondonRouteImport } from './routes/blog/roadside-puncture-repair-london'
import { Route as BlogRunFlatPunctureRepairLondonRouteImport } from './routes/blog/run-flat-puncture-repair-london'
import { Route as BlogRunFlatTyresUkGuideRouteImport } from './routes/blog/run-flat-tyres-uk-guide'
import { Route as BlogRunFlatVsStandardTyresRouteImport } from './routes/blog/run-flat-vs-standard-tyres'
import { Route as BlogSameDayPunctureRepairLondonRouteImport } from './routes/blog/same-day-puncture-repair-london'
import { Route as BlogSlowPunctureUkGuideRouteImport } from './routes/blog/slow-puncture-uk-guide'
import { Route as BlogTpmsWarningLightRouteImport } from './routes/blog/tpms-warning-light'
import { Route as BlogTwentyFourHourTyreChangeLondonRouteImport } from './routes/blog/twenty-four-hour-tyre-change-london'
import { Route as BlogTyreAgeWhenToReplaceRouteImport } from './routes/blog/tyre-age-when-to-replace'
import { Route as BlogTyreBlowoutOnMotorwayWhatToDoRouteImport } from './routes/blog/tyre-blowout-on-motorway-what-to-do'
import { Route as BlogTyreBulgeSidewallDangerRouteImport } from './routes/blog/tyre-bulge-sidewall-danger'
import { Route as BlogTyrePressureGuideUkRouteImport } from './routes/blog/tyre-pressure-guide-uk'
import { Route as BlogTyreSidewallDamageGuideRouteImport } from './routes/blog/tyre-sidewall-damage-guide'
import { Route as BlogUkTyreLegalTreadDepthRouteImport } from './routes/blog/uk-tyre-legal-tread-depth'
import { Route as BlogWheelAlignmentUkGuideRouteImport } from './routes/blog/wheel-alignment-uk-guide'
import { Route as JobIdRouteImport } from './routes/job/$id'
import { Route as PCodeRouteImport } from './routes/p/$code'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as TechnicianIndexRouteImport } from './routes/technician/index'
import { Route as TechnicianLoginRouteImport } from './routes/technician/login'
import { Route as TechnicianOnboardingRouteImport } from './routes/technician/onboarding'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin/dashboard/index'
import { Route as AdminDashboardActivityRouteImport } from './routes/admin/dashboard/activity'
import { Route as AdminDashboardAdminAiInstructionsRouteImport } from './routes/admin/dashboard/admin-ai-instructions'
import { Route as AdminDashboardAiSettingsRouteImport } from './routes/admin/dashboard/ai-settings'
import { Route as AdminDashboardCommandRouteImport } from './routes/admin/dashboard/command'
import { Route as AdminDashboardJobsRouteImport } from './routes/admin/dashboard/jobs'
import { Route as AdminDashboardPaymentsRouteImport } from './routes/admin/dashboard/payments'
import { Route as AdminDashboardQuotesRouteImport } from './routes/admin/dashboard/quotes'
import { Route as AdminDashboardReportsRouteImport } from './routes/admin/dashboard/reports'
import { Route as AdminDashboardSettingsRouteImport } from './routes/admin/dashboard/settings'
import { Route as AdminDashboardTechnicianAiInstructionsRouteImport } from './routes/admin/dashboard/technician-ai-instructions'
import { Route as AdminDashboardTechniciansRouteImport } from './routes/admin/dashboard/technicians'
import { Route as ServicesServiceIndexRouteImport } from './routes/services/$service/index'
import { Route as ServicesServiceCityRouteImport } from './routes/services/$service/$city'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmedRoute = ConfirmedRouteImport.update({
  id: '/confirmed',
  path: '/confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const Dash2Route = Dash2RouteImport.update({
  id: '/dash2',
  path: '/dash2',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasIndexRoute = AreasIndexRouteImport.update({
  id: '/areas/',
  path: '/areas/',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasSlugRoute = AreasSlugRouteImport.update({
  id: '/areas/$slug',
  path: '/areas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const Blog24HourPunctureRepairLondonRoute =
  Blog24HourPunctureRepairLondonRouteImport.update({
    id: '/blog/24-hour-puncture-repair-london',
    path: '/blog/24-hour-puncture-repair-london',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogAllSeasonVsWinterTyresUkRoute =
  BlogAllSeasonVsWinterTyresUkRouteImport.update({
    id: '/blog/all-season-vs-winter-tyres-uk',
    path: '/blog/all-season-vs-winter-tyres-uk',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogBudgetVsPremiumTyresUkRoute =
  BlogBudgetVsPremiumTyresUkRouteImport.update({
    id: '/blog/budget-vs-premium-tyres-uk',
    path: '/blog/budget-vs-premium-tyres-uk',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogCanAPunctureBeRepairedUkRoute =
  BlogCanAPunctureBeRepairedUkRouteImport.update({
    id: '/blog/can-a-puncture-be-repaired-uk',
    path: '/blog/can-a-puncture-be-repaired-uk',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogCanIDriveOnAFlatTyreUkRoute =
  BlogCanIDriveOnAFlatTyreUkRouteImport.update({
    id: '/blog/can-i-drive-on-a-flat-tyre-uk',
    path: '/blog/can-i-drive-on-a-flat-tyre-uk',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogCrackedAlloyFromPotholeRoute =
  BlogCrackedAlloyFromPotholeRouteImport.update({
    id: '/blog/cracked-alloy-from-pothole',
    path: '/blog/cracked-alloy-from-pothole',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogEmergencyPunctureRepairLondonRoute =
  BlogEmergencyPunctureRepairLondonRouteImport.update({
    id: '/blog/emergency-puncture-repair-london',
    path: '/blog/emergency-puncture-repair-london',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogFlatTyreLondonRoute = BlogFlatTyreLondonRouteImport.update({
  id: '/blog/flat-tyre-london',
  path: '/blog/flat-tyre-london',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogLockingWheelNutLostUkRoute =
  BlogLockingWheelNutLostUkRouteImport.update({
    id: '/blog/locking-wheel-nut-lost-uk',
    path: '/blog/locking-wheel-nut-lost-uk',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogMobilePunctureRepairLondonRoute =
  BlogMobilePunctureRepairLondonRouteImport.update({
    id: '/blog/mobile-puncture-repair-london',
    path: '/blog/mobile-puncture-repair-london',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogMobileTyreFitterM25Route = BlogMobileTyreFitterM25RouteImport.update({
  id: '/blog/mobile-tyre-fitter-m25',
  path: '/blog/mobile-tyre-fitter-m25',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogMobileTyreFitterVsGarageRoute =
  BlogMobileTyreFitterVsGarageRouteImport.update({
    id: '/blog/mobile-tyre-fitter-vs-garage',
    path: '/blog/mobile-tyre-fitter-vs-garage',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogMobileTyreFittingBirminghamRoute =
  BlogMobileTyreFittingBirminghamRouteImport.update({
    id: '/blog/mobile-tyre-fitting-birmingham',
    path: '/blog/mobile-tyre-fitting-birmingham',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogMobileTyreFittingLondonRoute =
  BlogMobileTyreFittingLondonRouteImport.update({
    id: '/blog/mobile-tyre-fitting-london',
    path: '/blog/mobile-tyre-fitting-london',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogMobileTyreFittingManchesterRoute =
  BlogMobileTyreFittingManchesterRouteImport.update({
    id: '/blog/mobile-tyre-fitting-manchester',
    path: '/blog/mobile-tyre-fitting-manchester',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogNailInTyreWhatToDoRoute = BlogNailInTyreWhatToDoRouteImport.update({
  id: '/blog/nail-in-tyre-what-to-do',
  path: '/blog/nail-in-tyre-what-to-do',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogPotholeDamageClaimUkRoute =
  BlogPotholeDamageClaimUkRouteImport.update({
    id: '/blog/pothole-damage-claim-uk',
    path: '/blog/pothole-damage-claim-uk',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogPunctureRepairCentralLondonRoute =
  BlogPunctureRepairCentralLondonRouteImport.update({
    id: '/blog/puncture-repair-central-london',
    path: '/blog/puncture-repair-central-london',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogPunctureRepairCostUkRoute =
  BlogPunctureRepairCostUkRouteImport.update({
    id: '/blog/puncture-repair-cost-uk',
    path: '/blog/puncture-repair-cost-uk',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogPunctureRepairVsNewTyreRoute =
  BlogPunctureRepairVsNewTyreRouteImport.update({
    id: '/blog/puncture-repair-vs-new-tyre',
    path: '/blog/puncture-repair-vs-new-tyre',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogRoadsidePunctureRepairLondonRoute =
  BlogRoadsidePunctureRepairLondonRouteImport.update({
    id: '/blog/roadside-puncture-repair-london',
    path: '/blog/roadside-puncture-repair-london',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogRunFlatPunctureRepairLondonRoute =
  BlogRunFlatPunctureRepairLondonRouteImport.update({
    id: '/blog/run-flat-puncture-repair-london',
    path: '/blog/run-flat-puncture-repair-london',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogRunFlatTyresUkGuideRoute = BlogRunFlatTyresUkGuideRouteImport.update({
  id: '/blog/run-flat-tyres-uk-guide',
  path: '/blog/run-flat-tyres-uk-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRunFlatVsStandardTyresRoute =
  BlogRunFlatVsStandardTyresRouteImport.update({
    id: '/blog/run-flat-vs-standard-tyres',
    path: '/blog/run-flat-vs-standard-tyres',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogSameDayPunctureRepairLondonRoute =
  BlogSameDayPunctureRepairLondonRouteImport.update({
    id: '/blog/same-day-puncture-repair-london',
    path: '/blog/same-day-puncture-repair-london',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogSlowPunctureUkGuideRoute = BlogSlowPunctureUkGuideRouteImport.update({
  id: '/blog/slow-puncture-uk-guide',
  path: '/blog/slow-puncture-uk-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogTpmsWarningLightRoute = BlogTpmsWarningLightRouteImport.update({
  id: '/blog/tpms-warning-light',
  path: '/blog/tpms-warning-light',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogTwentyFourHourTyreChangeLondonRoute =
  BlogTwentyFourHourTyreChangeLondonRouteImport.update({
    id: '/blog/twenty-four-hour-tyre-change-london',
    path: '/blog/twenty-four-hour-tyre-change-london',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogTyreAgeWhenToReplaceRoute =
  BlogTyreAgeWhenToReplaceRouteImport.update({
    id: '/blog/tyre-age-when-to-replace',
    path: '/blog/tyre-age-when-to-replace',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogTyreBlowoutOnMotorwayWhatToDoRoute =
  BlogTyreBlowoutOnMotorwayWhatToDoRouteImport.update({
    id: '/blog/tyre-blowout-on-motorway-what-to-do',
    path: '/blog/tyre-blowout-on-motorway-what-to-do',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogTyreBulgeSidewallDangerRoute =
  BlogTyreBulgeSidewallDangerRouteImport.update({
    id: '/blog/tyre-bulge-sidewall-danger',
    path: '/blog/tyre-bulge-sidewall-danger',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogTyrePressureGuideUkRoute = BlogTyrePressureGuideUkRouteImport.update({
  id: '/blog/tyre-pressure-guide-uk',
  path: '/blog/tyre-pressure-guide-uk',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogTyreSidewallDamageGuideRoute =
  BlogTyreSidewallDamageGuideRouteImport.update({
    id: '/blog/tyre-sidewall-damage-guide',
    path: '/blog/tyre-sidewall-damage-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogUkTyreLegalTreadDepthRoute =
  BlogUkTyreLegalTreadDepthRouteImport.update({
    id: '/blog/uk-tyre-legal-tread-depth',
    path: '/blog/uk-tyre-legal-tread-depth',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogWheelAlignmentUkGuideRoute =
  BlogWheelAlignmentUkGuideRouteImport.update({
    id: '/blog/wheel-alignment-uk-guide',
    path: '/blog/wheel-alignment-uk-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const JobIdRoute = JobIdRouteImport.update({
  id: '/job/$id',
  path: '/job/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PCodeRoute = PCodeRouteImport.update({
  id: '/p/$code',
  path: '/p/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicianIndexRoute = TechnicianIndexRouteImport.update({
  id: '/technician/',
  path: '/technician/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicianLoginRoute = TechnicianLoginRouteImport.update({
  id: '/technician/login',
  path: '/technician/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicianOnboardingRoute = TechnicianOnboardingRouteImport.update({
  id: '/technician/onboarding',
  path: '/technician/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardActivityRoute = AdminDashboardActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardAdminAiInstructionsRoute =
  AdminDashboardAdminAiInstructionsRouteImport.update({
    id: '/admin-ai-instructions',
    path: '/admin-ai-instructions',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardAiSettingsRoute =
  AdminDashboardAiSettingsRouteImport.update({
    id: '/ai-settings',
    path: '/ai-settings',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardCommandRoute = AdminDashboardCommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardJobsRoute = AdminDashboardJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardPaymentsRoute = AdminDashboardPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardQuotesRoute = AdminDashboardQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardReportsRoute = AdminDashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardSettingsRoute = AdminDashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardTechnicianAiInstructionsRoute =
  AdminDashboardTechnicianAiInstructionsRouteImport.update({
    id: '/technician-ai-instructions',
    path: '/technician-ai-instructions',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardTechniciansRoute =
  AdminDashboardTechniciansRouteImport.update({
    id: '/technicians',
    path: '/technicians',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const ServicesServiceIndexRoute = ServicesServiceIndexRouteImport.update({
  id: '/services/$service/',
  path: '/services/$service/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceCityRoute = ServicesServiceCityRouteImport.update({
  id: '/services/$service/$city',
  path: '/services/$service/$city',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confirmed': typeof ConfirmedRoute
  '/console': typeof ConsoleRoute
  '/dash2': typeof Dash2Route
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/dashboard': typeof AdminDashboardRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/areas/$slug': typeof AreasSlugRoute
  '/blog/24-hour-puncture-repair-london': typeof Blog24HourPunctureRepairLondonRoute
  '/blog/all-season-vs-winter-tyres-uk': typeof BlogAllSeasonVsWinterTyresUkRoute
  '/blog/budget-vs-premium-tyres-uk': typeof BlogBudgetVsPremiumTyresUkRoute
  '/blog/can-a-puncture-be-repaired-uk': typeof BlogCanAPunctureBeRepairedUkRoute
  '/blog/can-i-drive-on-a-flat-tyre-uk': typeof BlogCanIDriveOnAFlatTyreUkRoute
  '/blog/cracked-alloy-from-pothole': typeof BlogCrackedAlloyFromPotholeRoute
  '/blog/emergency-puncture-repair-london': typeof BlogEmergencyPunctureRepairLondonRoute
  '/blog/flat-tyre-london': typeof BlogFlatTyreLondonRoute
  '/blog/locking-wheel-nut-lost-uk': typeof BlogLockingWheelNutLostUkRoute
  '/blog/mobile-puncture-repair-london': typeof BlogMobilePunctureRepairLondonRoute
  '/blog/mobile-tyre-fitter-m25': typeof BlogMobileTyreFitterM25Route
  '/blog/mobile-tyre-fitter-vs-garage': typeof BlogMobileTyreFitterVsGarageRoute
  '/blog/mobile-tyre-fitting-birmingham': typeof BlogMobileTyreFittingBirminghamRoute
  '/blog/mobile-tyre-fitting-london': typeof BlogMobileTyreFittingLondonRoute
  '/blog/mobile-tyre-fitting-manchester': typeof BlogMobileTyreFittingManchesterRoute
  '/blog/nail-in-tyre-what-to-do': typeof BlogNailInTyreWhatToDoRoute
  '/blog/pothole-damage-claim-uk': typeof BlogPotholeDamageClaimUkRoute
  '/blog/puncture-repair-central-london': typeof BlogPunctureRepairCentralLondonRoute
  '/blog/puncture-repair-cost-uk': typeof BlogPunctureRepairCostUkRoute
  '/blog/puncture-repair-vs-new-tyre': typeof BlogPunctureRepairVsNewTyreRoute
  '/blog/roadside-puncture-repair-london': typeof BlogRoadsidePunctureRepairLondonRoute
  '/blog/run-flat-puncture-repair-london': typeof BlogRunFlatPunctureRepairLondonRoute
  '/blog/run-flat-tyres-uk-guide': typeof BlogRunFlatTyresUkGuideRoute
  '/blog/run-flat-vs-standard-tyres': typeof BlogRunFlatVsStandardTyresRoute
  '/blog/same-day-puncture-repair-london': typeof BlogSameDayPunctureRepairLondonRoute
  '/blog/slow-puncture-uk-guide': typeof BlogSlowPunctureUkGuideRoute
  '/blog/tpms-warning-light': typeof BlogTpmsWarningLightRoute
  '/blog/twenty-four-hour-tyre-change-london': typeof BlogTwentyFourHourTyreChangeLondonRoute
  '/blog/tyre-age-when-to-replace': typeof BlogTyreAgeWhenToReplaceRoute
  '/blog/tyre-blowout-on-motorway-what-to-do': typeof BlogTyreBlowoutOnMotorwayWhatToDoRoute
  '/blog/tyre-bulge-sidewall-danger': typeof BlogTyreBulgeSidewallDangerRoute
  '/blog/tyre-pressure-guide-uk': typeof BlogTyrePressureGuideUkRoute
  '/blog/tyre-sidewall-damage-guide': typeof BlogTyreSidewallDamageGuideRoute
  '/blog/uk-tyre-legal-tread-depth': typeof BlogUkTyreLegalTreadDepthRoute
  '/blog/wheel-alignment-uk-guide': typeof BlogWheelAlignmentUkGuideRoute
  '/job/$id': typeof JobIdRoute
  '/p/$code': typeof PCodeRoute
  '/technician/login': typeof TechnicianLoginRoute
  '/technician/onboarding': typeof TechnicianOnboardingRoute
  '/admin/': typeof AdminIndexRoute
  '/areas/': typeof AreasIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/technician/': typeof TechnicianIndexRoute
  '/admin/dashboard/activity': typeof AdminDashboardActivityRoute
  '/admin/dashboard/admin-ai-instructions': typeof AdminDashboardAdminAiInstructionsRoute
  '/admin/dashboard/ai-settings': typeof AdminDashboardAiSettingsRoute
  '/admin/dashboard/command': typeof AdminDashboardCommandRoute
  '/admin/dashboard/jobs': typeof AdminDashboardJobsRoute
  '/admin/dashboard/payments': typeof AdminDashboardPaymentsRoute
  '/admin/dashboard/quotes': typeof AdminDashboardQuotesRoute
  '/admin/dashboard/reports': typeof AdminDashboardReportsRoute
  '/admin/dashboard/settings': typeof AdminDashboardSettingsRoute
  '/admin/dashboard/technician-ai-instructions': typeof AdminDashboardTechnicianAiInstructionsRoute
  '/admin/dashboard/technicians': typeof AdminDashboardTechniciansRoute
  '/services/$service/$city': typeof ServicesServiceCityRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/services/$service/': typeof ServicesServiceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirmed': typeof ConfirmedRoute
  '/console': typeof ConsoleRoute
  '/dash2': typeof Dash2Route
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/areas/$slug': typeof AreasSlugRoute
  '/blog/24-hour-puncture-repair-london': typeof Blog24HourPunctureRepairLondonRoute
  '/blog/all-season-vs-winter-tyres-uk': typeof BlogAllSeasonVsWinterTyresUkRoute
  '/blog/budget-vs-premium-tyres-uk': typeof BlogBudgetVsPremiumTyresUkRoute
  '/blog/can-a-puncture-be-repaired-uk': typeof BlogCanAPunctureBeRepairedUkRoute
  '/blog/can-i-drive-on-a-flat-tyre-uk': typeof BlogCanIDriveOnAFlatTyreUkRoute
  '/blog/cracked-alloy-from-pothole': typeof BlogCrackedAlloyFromPotholeRoute
  '/blog/emergency-puncture-repair-london': typeof BlogEmergencyPunctureRepairLondonRoute
  '/blog/flat-tyre-london': typeof BlogFlatTyreLondonRoute
  '/blog/locking-wheel-nut-lost-uk': typeof BlogLockingWheelNutLostUkRoute
  '/blog/mobile-puncture-repair-london': typeof BlogMobilePunctureRepairLondonRoute
  '/blog/mobile-tyre-fitter-m25': typeof BlogMobileTyreFitterM25Route
  '/blog/mobile-tyre-fitter-vs-garage': typeof BlogMobileTyreFitterVsGarageRoute
  '/blog/mobile-tyre-fitting-birmingham': typeof BlogMobileTyreFittingBirminghamRoute
  '/blog/mobile-tyre-fitting-london': typeof BlogMobileTyreFittingLondonRoute
  '/blog/mobile-tyre-fitting-manchester': typeof BlogMobileTyreFittingManchesterRoute
  '/blog/nail-in-tyre-what-to-do': typeof BlogNailInTyreWhatToDoRoute
  '/blog/pothole-damage-claim-uk': typeof BlogPotholeDamageClaimUkRoute
  '/blog/puncture-repair-central-london': typeof BlogPunctureRepairCentralLondonRoute
  '/blog/puncture-repair-cost-uk': typeof BlogPunctureRepairCostUkRoute
  '/blog/puncture-repair-vs-new-tyre': typeof BlogPunctureRepairVsNewTyreRoute
  '/blog/roadside-puncture-repair-london': typeof BlogRoadsidePunctureRepairLondonRoute
  '/blog/run-flat-puncture-repair-london': typeof BlogRunFlatPunctureRepairLondonRoute
  '/blog/run-flat-tyres-uk-guide': typeof BlogRunFlatTyresUkGuideRoute
  '/blog/run-flat-vs-standard-tyres': typeof BlogRunFlatVsStandardTyresRoute
  '/blog/same-day-puncture-repair-london': typeof BlogSameDayPunctureRepairLondonRoute
  '/blog/slow-puncture-uk-guide': typeof BlogSlowPunctureUkGuideRoute
  '/blog/tpms-warning-light': typeof BlogTpmsWarningLightRoute
  '/blog/twenty-four-hour-tyre-change-london': typeof BlogTwentyFourHourTyreChangeLondonRoute
  '/blog/tyre-age-when-to-replace': typeof BlogTyreAgeWhenToReplaceRoute
  '/blog/tyre-blowout-on-motorway-what-to-do': typeof BlogTyreBlowoutOnMotorwayWhatToDoRoute
  '/blog/tyre-bulge-sidewall-danger': typeof BlogTyreBulgeSidewallDangerRoute
  '/blog/tyre-pressure-guide-uk': typeof BlogTyrePressureGuideUkRoute
  '/blog/tyre-sidewall-damage-guide': typeof BlogTyreSidewallDamageGuideRoute
  '/blog/uk-tyre-legal-tread-depth': typeof BlogUkTyreLegalTreadDepthRoute
  '/blog/wheel-alignment-uk-guide': typeof BlogWheelAlignmentUkGuideRoute
  '/job/$id': typeof JobIdRoute
  '/p/$code': typeof PCodeRoute
  '/technician/login': typeof TechnicianLoginRoute
  '/technician/onboarding': typeof TechnicianOnboardingRoute
  '/admin': typeof AdminIndexRoute
  '/areas': typeof AreasIndexRoute
  '/blog': typeof BlogIndexRoute
  '/services': typeof ServicesIndexRoute
  '/technician': typeof TechnicianIndexRoute
  '/admin/dashboard/activity': typeof AdminDashboardActivityRoute
  '/admin/dashboard/admin-ai-instructions': typeof AdminDashboardAdminAiInstructionsRoute
  '/admin/dashboard/ai-settings': typeof AdminDashboardAiSettingsRoute
  '/admin/dashboard/command': typeof AdminDashboardCommandRoute
  '/admin/dashboard/jobs': typeof AdminDashboardJobsRoute
  '/admin/dashboard/payments': typeof AdminDashboardPaymentsRoute
  '/admin/dashboard/quotes': typeof AdminDashboardQuotesRoute
  '/admin/dashboard/reports': typeof AdminDashboardReportsRoute
  '/admin/dashboard/settings': typeof AdminDashboardSettingsRoute
  '/admin/dashboard/technician-ai-instructions': typeof AdminDashboardTechnicianAiInstructionsRoute
  '/admin/dashboard/technicians': typeof AdminDashboardTechniciansRoute
  '/services/$service/$city': typeof ServicesServiceCityRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/services/$service': typeof ServicesServiceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/confirmed': typeof ConfirmedRoute
  '/console': typeof ConsoleRoute
  '/dash2': typeof Dash2Route
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/dashboard': typeof AdminDashboardRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/areas/$slug': typeof AreasSlugRoute
  '/blog/24-hour-puncture-repair-london': typeof Blog24HourPunctureRepairLondonRoute
  '/blog/all-season-vs-winter-tyres-uk': typeof BlogAllSeasonVsWinterTyresUkRoute
  '/blog/budget-vs-premium-tyres-uk': typeof BlogBudgetVsPremiumTyresUkRoute
  '/blog/can-a-puncture-be-repaired-uk': typeof BlogCanAPunctureBeRepairedUkRoute
  '/blog/can-i-drive-on-a-flat-tyre-uk': typeof BlogCanIDriveOnAFlatTyreUkRoute
  '/blog/cracked-alloy-from-pothole': typeof BlogCrackedAlloyFromPotholeRoute
  '/blog/emergency-puncture-repair-london': typeof BlogEmergencyPunctureRepairLondonRoute
  '/blog/flat-tyre-london': typeof BlogFlatTyreLondonRoute
  '/blog/locking-wheel-nut-lost-uk': typeof BlogLockingWheelNutLostUkRoute
  '/blog/mobile-puncture-repair-london': typeof BlogMobilePunctureRepairLondonRoute
  '/blog/mobile-tyre-fitter-m25': typeof BlogMobileTyreFitterM25Route
  '/blog/mobile-tyre-fitter-vs-garage': typeof BlogMobileTyreFitterVsGarageRoute
  '/blog/mobile-tyre-fitting-birmingham': typeof BlogMobileTyreFittingBirminghamRoute
  '/blog/mobile-tyre-fitting-london': typeof BlogMobileTyreFittingLondonRoute
  '/blog/mobile-tyre-fitting-manchester': typeof BlogMobileTyreFittingManchesterRoute
  '/blog/nail-in-tyre-what-to-do': typeof BlogNailInTyreWhatToDoRoute
  '/blog/pothole-damage-claim-uk': typeof BlogPotholeDamageClaimUkRoute
  '/blog/puncture-repair-central-london': typeof BlogPunctureRepairCentralLondonRoute
  '/blog/puncture-repair-cost-uk': typeof BlogPunctureRepairCostUkRoute
  '/blog/puncture-repair-vs-new-tyre': typeof BlogPunctureRepairVsNewTyreRoute
  '/blog/roadside-puncture-repair-london': typeof BlogRoadsidePunctureRepairLondonRoute
  '/blog/run-flat-puncture-repair-london': typeof BlogRunFlatPunctureRepairLondonRoute
  '/blog/run-flat-tyres-uk-guide': typeof BlogRunFlatTyresUkGuideRoute
  '/blog/run-flat-vs-standard-tyres': typeof BlogRunFlatVsStandardTyresRoute
  '/blog/same-day-puncture-repair-london': typeof BlogSameDayPunctureRepairLondonRoute
  '/blog/slow-puncture-uk-guide': typeof BlogSlowPunctureUkGuideRoute
  '/blog/tpms-warning-light': typeof BlogTpmsWarningLightRoute
  '/blog/twenty-four-hour-tyre-change-london': typeof BlogTwentyFourHourTyreChangeLondonRoute
  '/blog/tyre-age-when-to-replace': typeof BlogTyreAgeWhenToReplaceRoute
  '/blog/tyre-blowout-on-motorway-what-to-do': typeof BlogTyreBlowoutOnMotorwayWhatToDoRoute
  '/blog/tyre-bulge-sidewall-danger': typeof BlogTyreBulgeSidewallDangerRoute
  '/blog/tyre-pressure-guide-uk': typeof BlogTyrePressureGuideUkRoute
  '/blog/tyre-sidewall-damage-guide': typeof BlogTyreSidewallDamageGuideRoute
  '/blog/uk-tyre-legal-tread-depth': typeof BlogUkTyreLegalTreadDepthRoute
  '/blog/wheel-alignment-uk-guide': typeof BlogWheelAlignmentUkGuideRoute
  '/job/$id': typeof JobIdRoute
  '/p/$code': typeof PCodeRoute
  '/technician/login': typeof TechnicianLoginRoute
  '/technician/onboarding': typeof TechnicianOnboardingRoute
  '/admin/': typeof AdminIndexRoute
  '/areas/': typeof AreasIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/technician/': typeof TechnicianIndexRoute
  '/admin/dashboard/activity': typeof AdminDashboardActivityRoute
  '/admin/dashboard/admin-ai-instructions': typeof AdminDashboardAdminAiInstructionsRoute
  '/admin/dashboard/ai-settings': typeof AdminDashboardAiSettingsRoute
  '/admin/dashboard/command': typeof AdminDashboardCommandRoute
  '/admin/dashboard/jobs': typeof AdminDashboardJobsRoute
  '/admin/dashboard/payments': typeof AdminDashboardPaymentsRoute
  '/admin/dashboard/quotes': typeof AdminDashboardQuotesRoute
  '/admin/dashboard/reports': typeof AdminDashboardReportsRoute
  '/admin/dashboard/settings': typeof AdminDashboardSettingsRoute
  '/admin/dashboard/technician-ai-instructions': typeof AdminDashboardTechnicianAiInstructionsRoute
  '/admin/dashboard/technicians': typeof AdminDashboardTechniciansRoute
  '/services/$service/$city': typeof ServicesServiceCityRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/services/$service/': typeof ServicesServiceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confirmed'
    | '/console'
    | '/dash2'
    | '/privacy'
    | '/terms'
    | '/admin/dashboard'
    | '/admin/login'
    | '/areas/$slug'
    | '/blog/24-hour-puncture-repair-london'
    | '/blog/all-season-vs-winter-tyres-uk'
    | '/blog/budget-vs-premium-tyres-uk'
    | '/blog/can-a-puncture-be-repaired-uk'
    | '/blog/can-i-drive-on-a-flat-tyre-uk'
    | '/blog/cracked-alloy-from-pothole'
    | '/blog/emergency-puncture-repair-london'
    | '/blog/flat-tyre-london'
    | '/blog/locking-wheel-nut-lost-uk'
    | '/blog/mobile-puncture-repair-london'
    | '/blog/mobile-tyre-fitter-m25'
    | '/blog/mobile-tyre-fitter-vs-garage'
    | '/blog/mobile-tyre-fitting-birmingham'
    | '/blog/mobile-tyre-fitting-london'
    | '/blog/mobile-tyre-fitting-manchester'
    | '/blog/nail-in-tyre-what-to-do'
    | '/blog/pothole-damage-claim-uk'
    | '/blog/puncture-repair-central-london'
    | '/blog/puncture-repair-cost-uk'
    | '/blog/puncture-repair-vs-new-tyre'
    | '/blog/roadside-puncture-repair-london'
    | '/blog/run-flat-puncture-repair-london'
    | '/blog/run-flat-tyres-uk-guide'
    | '/blog/run-flat-vs-standard-tyres'
    | '/blog/same-day-puncture-repair-london'
    | '/blog/slow-puncture-uk-guide'
    | '/blog/tpms-warning-light'
    | '/blog/twenty-four-hour-tyre-change-london'
    | '/blog/tyre-age-when-to-replace'
    | '/blog/tyre-blowout-on-motorway-what-to-do'
    | '/blog/tyre-bulge-sidewall-danger'
    | '/blog/tyre-pressure-guide-uk'
    | '/blog/tyre-sidewall-damage-guide'
    | '/blog/uk-tyre-legal-tread-depth'
    | '/blog/wheel-alignment-uk-guide'
    | '/job/$id'
    | '/p/$code'
    | '/technician/login'
    | '/technician/onboarding'
    | '/admin/'
    | '/areas/'
    | '/blog/'
    | '/services/'
    | '/technician/'
    | '/admin/dashboard/activity'
    | '/admin/dashboard/admin-ai-instructions'
    | '/admin/dashboard/ai-settings'
    | '/admin/dashboard/command'
    | '/admin/dashboard/jobs'
    | '/admin/dashboard/payments'
    | '/admin/dashboard/quotes'
    | '/admin/dashboard/reports'
    | '/admin/dashboard/settings'
    | '/admin/dashboard/technician-ai-instructions'
    | '/admin/dashboard/technicians'
    | '/services/$service/$city'
    | '/admin/dashboard/'
    | '/services/$service/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confirmed'
    | '/console'
    | '/dash2'
    | '/privacy'
    | '/terms'
    | '/admin/login'
    | '/areas/$slug'
    | '/blog/24-hour-puncture-repair-london'
    | '/blog/all-season-vs-winter-tyres-uk'
    | '/blog/budget-vs-premium-tyres-uk'
    | '/blog/can-a-puncture-be-repaired-uk'
    | '/blog/can-i-drive-on-a-flat-tyre-uk'
    | '/blog/cracked-alloy-from-pothole'
    | '/blog/emergency-puncture-repair-london'
    | '/blog/flat-tyre-london'
    | '/blog/locking-wheel-nut-lost-uk'
    | '/blog/mobile-puncture-repair-london'
    | '/blog/mobile-tyre-fitter-m25'
    | '/blog/mobile-tyre-fitter-vs-garage'
    | '/blog/mobile-tyre-fitting-birmingham'
    | '/blog/mobile-tyre-fitting-london'
    | '/blog/mobile-tyre-fitting-manchester'
    | '/blog/nail-in-tyre-what-to-do'
    | '/blog/pothole-damage-claim-uk'
    | '/blog/puncture-repair-central-london'
    | '/blog/puncture-repair-cost-uk'
    | '/blog/puncture-repair-vs-new-tyre'
    | '/blog/roadside-puncture-repair-london'
    | '/blog/run-flat-puncture-repair-london'
    | '/blog/run-flat-tyres-uk-guide'
    | '/blog/run-flat-vs-standard-tyres'
    | '/blog/same-day-puncture-repair-london'
    | '/blog/slow-puncture-uk-guide'
    | '/blog/tpms-warning-light'
    | '/blog/twenty-four-hour-tyre-change-london'
    | '/blog/tyre-age-when-to-replace'
    | '/blog/tyre-blowout-on-motorway-what-to-do'
    | '/blog/tyre-bulge-sidewall-danger'
    | '/blog/tyre-pressure-guide-uk'
    | '/blog/tyre-sidewall-damage-guide'
    | '/blog/uk-tyre-legal-tread-depth'
    | '/blog/wheel-alignment-uk-guide'
    | '/job/$id'
    | '/p/$code'
    | '/technician/login'
    | '/technician/onboarding'
    | '/admin'
    | '/areas'
    | '/blog'
    | '/services'
    | '/technician'
    | '/admin/dashboard/activity'
    | '/admin/dashboard/admin-ai-instructions'
    | '/admin/dashboard/ai-settings'
    | '/admin/dashboard/command'
    | '/admin/dashboard/jobs'
    | '/admin/dashboard/payments'
    | '/admin/dashboard/quotes'
    | '/admin/dashboard/reports'
    | '/admin/dashboard/settings'
    | '/admin/dashboard/technician-ai-instructions'
    | '/admin/dashboard/technicians'
    | '/services/$service/$city'
    | '/admin/dashboard'
    | '/services/$service'
  id:
    | '__root__'
    | '/'
    | '/confirmed'
    | '/console'
    | '/dash2'
    | '/privacy'
    | '/terms'
    | '/admin/dashboard'
    | '/admin/login'
    | '/areas/$slug'
    | '/blog/24-hour-puncture-repair-london'
    | '/blog/all-season-vs-winter-tyres-uk'
    | '/blog/budget-vs-premium-tyres-uk'
    | '/blog/can-a-puncture-be-repaired-uk'
    | '/blog/can-i-drive-on-a-flat-tyre-uk'
    | '/blog/cracked-alloy-from-pothole'
    | '/blog/emergency-puncture-repair-london'
    | '/blog/flat-tyre-london'
    | '/blog/locking-wheel-nut-lost-uk'
    | '/blog/mobile-puncture-repair-london'
    | '/blog/mobile-tyre-fitter-m25'
    | '/blog/mobile-tyre-fitter-vs-garage'
    | '/blog/mobile-tyre-fitting-birmingham'
    | '/blog/mobile-tyre-fitting-london'
    | '/blog/mobile-tyre-fitting-manchester'
    | '/blog/nail-in-tyre-what-to-do'
    | '/blog/pothole-damage-claim-uk'
    | '/blog/puncture-repair-central-london'
    | '/blog/puncture-repair-cost-uk'
    | '/blog/puncture-repair-vs-new-tyre'
    | '/blog/roadside-puncture-repair-london'
    | '/blog/run-flat-puncture-repair-london'
    | '/blog/run-flat-tyres-uk-guide'
    | '/blog/run-flat-vs-standard-tyres'
    | '/blog/same-day-puncture-repair-london'
    | '/blog/slow-puncture-uk-guide'
    | '/blog/tpms-warning-light'
    | '/blog/twenty-four-hour-tyre-change-london'
    | '/blog/tyre-age-when-to-replace'
    | '/blog/tyre-blowout-on-motorway-what-to-do'
    | '/blog/tyre-bulge-sidewall-danger'
    | '/blog/tyre-pressure-guide-uk'
    | '/blog/tyre-sidewall-damage-guide'
    | '/blog/uk-tyre-legal-tread-depth'
    | '/blog/wheel-alignment-uk-guide'
    | '/job/$id'
    | '/p/$code'
    | '/technician/login'
    | '/technician/onboarding'
    | '/admin/'
    | '/areas/'
    | '/blog/'
    | '/services/'
    | '/technician/'
    | '/admin/dashboard/activity'
    | '/admin/dashboard/admin-ai-instructions'
    | '/admin/dashboard/ai-settings'
    | '/admin/dashboard/command'
    | '/admin/dashboard/jobs'
    | '/admin/dashboard/payments'
    | '/admin/dashboard/quotes'
    | '/admin/dashboard/reports'
    | '/admin/dashboard/settings'
    | '/admin/dashboard/technician-ai-instructions'
    | '/admin/dashboard/technicians'
    | '/services/$service/$city'
    | '/admin/dashboard/'
    | '/services/$service/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfirmedRoute: typeof ConfirmedRoute
  ConsoleRoute: typeof ConsoleRoute
  Dash2Route: typeof Dash2Route
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AdminDashboardRoute: typeof AdminDashboardRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AreasSlugRoute: typeof AreasSlugRoute
  Blog24HourPunctureRepairLondonRoute: typeof Blog24HourPunctureRepairLondonRoute
  BlogAllSeasonVsWinterTyresUkRoute: typeof BlogAllSeasonVsWinterTyresUkRoute
  BlogBudgetVsPremiumTyresUkRoute: typeof BlogBudgetVsPremiumTyresUkRoute
  BlogCanAPunctureBeRepairedUkRoute: typeof BlogCanAPunctureBeRepairedUkRoute
  BlogCanIDriveOnAFlatTyreUkRoute: typeof BlogCanIDriveOnAFlatTyreUkRoute
  BlogCrackedAlloyFromPotholeRoute: typeof BlogCrackedAlloyFromPotholeRoute
  BlogEmergencyPunctureRepairLondonRoute: typeof BlogEmergencyPunctureRepairLondonRoute
  BlogFlatTyreLondonRoute: typeof BlogFlatTyreLondonRoute
  BlogLockingWheelNutLostUkRoute: typeof BlogLockingWheelNutLostUkRoute
  BlogMobilePunctureRepairLondonRoute: typeof BlogMobilePunctureRepairLondonRoute
  BlogMobileTyreFitterM25Route: typeof BlogMobileTyreFitterM25Route
  BlogMobileTyreFitterVsGarageRoute: typeof BlogMobileTyreFitterVsGarageRoute
  BlogMobileTyreFittingBirminghamRoute: typeof BlogMobileTyreFittingBirminghamRoute
  BlogMobileTyreFittingLondonRoute: typeof BlogMobileTyreFittingLondonRoute
  BlogMobileTyreFittingManchesterRoute: typeof BlogMobileTyreFittingManchesterRoute
  BlogNailInTyreWhatToDoRoute: typeof BlogNailInTyreWhatToDoRoute
  BlogPotholeDamageClaimUkRoute: typeof BlogPotholeDamageClaimUkRoute
  BlogPunctureRepairCentralLondonRoute: typeof BlogPunctureRepairCentralLondonRoute
  BlogPunctureRepairCostUkRoute: typeof BlogPunctureRepairCostUkRoute
  BlogPunctureRepairVsNewTyreRoute: typeof BlogPunctureRepairVsNewTyreRoute
  BlogRoadsidePunctureRepairLondonRoute: typeof BlogRoadsidePunctureRepairLondonRoute
  BlogRunFlatPunctureRepairLondonRoute: typeof BlogRunFlatPunctureRepairLondonRoute
  BlogRunFlatTyresUkGuideRoute: typeof BlogRunFlatTyresUkGuideRoute
  BlogRunFlatVsStandardTyresRoute: typeof BlogRunFlatVsStandardTyresRoute
  BlogSameDayPunctureRepairLondonRoute: typeof BlogSameDayPunctureRepairLondonRoute
  BlogSlowPunctureUkGuideRoute: typeof BlogSlowPunctureUkGuideRoute
  BlogTpmsWarningLightRoute: typeof BlogTpmsWarningLightRoute
  BlogTwentyFourHourTyreChangeLondonRoute: typeof BlogTwentyFourHourTyreChangeLondonRoute
  BlogTyreAgeWhenToReplaceRoute: typeof BlogTyreAgeWhenToReplaceRoute
  BlogTyreBlowoutOnMotorwayWhatToDoRoute: typeof BlogTyreBlowoutOnMotorwayWhatToDoRoute
  BlogTyreBulgeSidewallDangerRoute: typeof BlogTyreBulgeSidewallDangerRoute
  BlogTyrePressureGuideUkRoute: typeof BlogTyrePressureGuideUkRoute
  BlogTyreSidewallDamageGuideRoute: typeof BlogTyreSidewallDamageGuideRoute
  BlogUkTyreLegalTreadDepthRoute: typeof BlogUkTyreLegalTreadDepthRoute
  BlogWheelAlignmentUkGuideRoute: typeof BlogWheelAlignmentUkGuideRoute
  JobIdRoute: typeof JobIdRoute
  PCodeRoute: typeof PCodeRoute
  TechnicianLoginRoute: typeof TechnicianLoginRoute
  TechnicianOnboardingRoute: typeof TechnicianOnboardingRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AreasIndexRoute: typeof AreasIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  TechnicianIndexRoute: typeof TechnicianIndexRoute
  ServicesServiceCityRoute: typeof ServicesServiceCityRoute
  ServicesServiceIndexRoute: typeof ServicesServiceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmed': {
      id: '/confirmed'
      path: '/confirmed'
      fullPath: '/confirmed'
      preLoaderRoute: typeof ConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash2': {
      id: '/dash2'
      path: '/dash2'
      fullPath: '/dash2'
      preLoaderRoute: typeof Dash2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/': {
      id: '/areas/'
      path: '/areas'
      fullPath: '/areas/'
      preLoaderRoute: typeof AreasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/$slug': {
      id: '/areas/$slug'
      path: '/areas/$slug'
      fullPath: '/areas/$slug'
      preLoaderRoute: typeof AreasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/24-hour-puncture-repair-london': {
      id: '/blog/24-hour-puncture-repair-london'
      path: '/blog/24-hour-puncture-repair-london'
      fullPath: '/blog/24-hour-puncture-repair-london'
      preLoaderRoute: typeof Blog24HourPunctureRepairLondonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/all-season-vs-winter-tyres-uk': {
      id: '/blog/all-season-vs-winter-tyres-uk'
      path: '/blog/all-season-vs-winter-tyres-uk'
      fullPath: '/blog/all-season-vs-winter-tyres-uk'
      preLoaderRoute: typeof BlogAllSeasonVsWinterTyresUkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/budget-vs-premium-tyres-uk': {
      id: '/blog/budget-vs-premium-tyres-uk'
      path: '/blog/budget-vs-premium-tyres-uk'
      fullPath: '/blog/budget-vs-premium-tyres-uk'
      preLoaderRoute: typeof BlogBudgetVsPremiumTyresUkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/can-a-puncture-be-repaired-uk': {
      id: '/blog/can-a-puncture-be-repaired-uk'
      path: '/blog/can-a-puncture-be-repaired-uk'
      fullPath: '/blog/can-a-puncture-be-repaired-uk'
      preLoaderRoute: typeof BlogCanAPunctureBeRepairedUkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/can-i-drive-on-a-flat-tyre-uk': {
      id: '/blog/can-i-drive-on-a-flat-tyre-uk'
      path: '/blog/can-i-drive-on-a-flat-tyre-uk'
      fullPath: '/blog/can-i-drive-on-a-flat-tyre-uk'
      preLoaderRoute: typeof BlogCanIDriveOnAFlatTyreUkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/cracked-alloy-from-pothole': {
      id: '/blog/cracked-alloy-from-pothole'
      path: '/blog/cracked-alloy-from-pothole'
      fullPath: '/blog/cracked-alloy-from-pothole'
      preLoaderRoute: typeof BlogCrackedAlloyFromPotholeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/emergency-puncture-repair-london': {
      id: '/blog/emergency-puncture-repair-london'
      path: '/blog/emergency-puncture-repair-london'
      fullPath: '/blog/emergency-puncture-repair-london'
      preLoaderRoute: typeof BlogEmergencyPunctureRepairLondonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/flat-tyre-london': {
      id: '/blog/flat-tyre-london'
      path: '/blog/flat-tyre-london'
      fullPath: '/blog/flat-tyre-london'
      preLoaderRoute: typeof BlogFlatTyreLondonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/locking-wheel-nut-lost-uk': {
      id: '/blog/locking-wheel-nut-lost-uk'
      path: '/blog/locking-wheel-nut-lost-uk'
      fullPath: '/blog/locking-wheel-nut-lost-uk'
      preLoaderRoute: typeof BlogLockingWheelNutLostUkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/mobile-puncture-repair-london': {
      id: '/blog/mobile-puncture-repair-london'
      path: '/blog/mobile-puncture-repair-london'
      fullPath: '/blog/mobile-puncture-repair-london'
      preLoaderRoute: typeof BlogMobilePunctureRepairLondonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/mobile-tyre-fitter-m25': {
      id: '/blog/mobile-tyre-fitter-m25'
      path: '/blog/mobile-tyre-fitter-m25'
      fullPath: '/blog/mobile-tyre-fitter-m25'
      preLoaderRoute: typeof BlogMobileTyreFitterM25RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/mobile-tyre-fitter-vs-garage': {
      id: '/blog/mobile-tyre-fitter-vs-garage'
      path: '/blog/mobile-tyre-fitter-vs-garage'
      fullPath: '/blog/mobile-tyre-fitter-vs-garage'
      preLoaderRoute: typeof BlogMobileTyreFitterVsGarageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/mobile-tyre-fitting-birmingham': {
      id: '/blog/mobile-tyre-fitting-birmingham'
      path: '/blog/mobile-tyre-fitting-birmingham'
      fullPath: '/blog/mobile-tyre-fitting-birmingham'
      preLoaderRoute: typeof BlogMobileTyreFittingBirminghamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/mobile-tyre-fitting-london': {
      id: '/blog/mobile-tyre-fitting-london'
      path: '/blog/mobile-tyre-fitting-london'
      fullPath: '/blog/mobile-tyre-fitting-london'
      preLoaderRoute: typeof BlogMobileTyreFittingLondonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/mobile-tyre-fitting-manchester': {
      id: '/blog/mobile-tyre-fitting-manchester'
      path: '/blog/mobile-tyre-fitting-manchester'
      fullPath: '/blog/mobile-tyre-fitting-manchester'
      preLoaderRoute: typeof BlogMobileTyreFittingManchesterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/nail-in-tyre-what-to-do': {
      id: '/blog/nail-in-tyre-what-to-do'
      path: '/blog/nail-in-tyre-what-to-do'
      fullPath: '/blog/nail-in-tyre-what-to-do'
      preLoaderRoute: typeof BlogNailInTyreWhatToDoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/pothole-damage-claim-uk': {
      id: '/blog/pothole-damage-claim-uk'
      path: '/blog/pothole-damage-claim-uk'
      fullPath: '/blog/pothole-damage-claim-uk'
      preLoaderRoute: typeof BlogPotholeDamageClaimUkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/puncture-repair-central-london': {
      id: '/blog/puncture-repair-central-london'
      path: '/blog/puncture-repair-central-london'
      fullPath: '/blog/puncture-repair-central-london'
      preLoaderRoute: typeof BlogPunctureRepairCentralLondonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/puncture-repair-cost-uk': {
      id: '/blog/puncture-repair-cost-uk'
      path: '/blog/puncture-repair-cost-uk'
      fullPath: '/blog/puncture-repair-cost-uk'
      preLoaderRoute: typeof BlogPunctureRepairCostUkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/puncture-repair-vs-new-tyre': {
      id: '/blog/puncture-repair-vs-new-tyre'
      path: '/blog/puncture-repair-vs-new-tyre'
      fullPath: '/blog/puncture-repair-vs-new-tyre'
      preLoaderRoute: typeof BlogPunctureRepairVsNewTyreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/roadside-puncture-repair-london': {
      id: '/blog/roadside-puncture-repair-london'
      path: '/blog/roadside-puncture-repair-london'
      fullPath: '/blog/roadside-puncture-repair-london'
      preLoaderRoute: typeof BlogRoadsidePunctureRepairLondonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/run-flat-puncture-repair-london': {
      id: '/blog/run-flat-puncture-repair-london'
      path: '/blog/run-flat-puncture-repair-london'
      fullPath: '/blog/run-flat-puncture-repair-london'
      preLoaderRoute: typeof BlogRunFlatPunctureRepairLondonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/run-flat-tyres-uk-guide': {
      id: '/blog/run-flat-tyres-uk-guide'
      path: '/blog/run-flat-tyres-uk-guide'
      fullPath: '/blog/run-flat-tyres-uk-guide'
      preLoaderRoute: typeof BlogRunFlatTyresUkGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/run-flat-vs-standard-tyres': {
      id: '/blog/run-flat-vs-standard-tyres'
      path: '/blog/run-flat-vs-standard-tyres'
      fullPath: '/blog/run-flat-vs-standard-tyres'
      preLoaderRoute: typeof BlogRunFlatVsStandardTyresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/same-day-puncture-repair-london': {
      id: '/blog/same-day-puncture-repair-london'
      path: '/blog/same-day-puncture-repair-london'
      fullPath: '/blog/same-day-puncture-repair-london'
      preLoaderRoute: typeof BlogSameDayPunctureRepairLondonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/slow-puncture-uk-guide': {
      id: '/blog/slow-puncture-uk-guide'
      path: '/blog/slow-puncture-uk-guide'
      fullPath: '/blog/slow-puncture-uk-guide'
      preLoaderRoute: typeof BlogSlowPunctureUkGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/tpms-warning-light': {
      id: '/blog/tpms-warning-light'
      path: '/blog/tpms-warning-light'
      fullPath: '/blog/tpms-warning-light'
      preLoaderRoute: typeof BlogTpmsWarningLightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/twenty-four-hour-tyre-change-london': {
      id: '/blog/twenty-four-hour-tyre-change-london'
      path: '/blog/twenty-four-hour-tyre-change-london'
      fullPath: '/blog/twenty-four-hour-tyre-change-london'
      preLoaderRoute: typeof BlogTwentyFourHourTyreChangeLondonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/tyre-age-when-to-replace': {
      id: '/blog/tyre-age-when-to-replace'
      path: '/blog/tyre-age-when-to-replace'
      fullPath: '/blog/tyre-age-when-to-replace'
      preLoaderRoute: typeof BlogTyreAgeWhenToReplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/tyre-blowout-on-motorway-what-to-do': {
      id: '/blog/tyre-blowout-on-motorway-what-to-do'
      path: '/blog/tyre-blowout-on-motorway-what-to-do'
      fullPath: '/blog/tyre-blowout-on-motorway-what-to-do'
      preLoaderRoute: typeof BlogTyreBlowoutOnMotorwayWhatToDoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/tyre-bulge-sidewall-danger': {
      id: '/blog/tyre-bulge-sidewall-danger'
      path: '/blog/tyre-bulge-sidewall-danger'
      fullPath: '/blog/tyre-bulge-sidewall-danger'
      preLoaderRoute: typeof BlogTyreBulgeSidewallDangerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/tyre-pressure-guide-uk': {
      id: '/blog/tyre-pressure-guide-uk'
      path: '/blog/tyre-pressure-guide-uk'
      fullPath: '/blog/tyre-pressure-guide-uk'
      preLoaderRoute: typeof BlogTyrePressureGuideUkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/tyre-sidewall-damage-guide': {
      id: '/blog/tyre-sidewall-damage-guide'
      path: '/blog/tyre-sidewall-damage-guide'
      fullPath: '/blog/tyre-sidewall-damage-guide'
      preLoaderRoute: typeof BlogTyreSidewallDamageGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/uk-tyre-legal-tread-depth': {
      id: '/blog/uk-tyre-legal-tread-depth'
      path: '/blog/uk-tyre-legal-tread-depth'
      fullPath: '/blog/uk-tyre-legal-tread-depth'
      preLoaderRoute: typeof BlogUkTyreLegalTreadDepthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/wheel-alignment-uk-guide': {
      id: '/blog/wheel-alignment-uk-guide'
      path: '/blog/wheel-alignment-uk-guide'
      fullPath: '/blog/wheel-alignment-uk-guide'
      preLoaderRoute: typeof BlogWheelAlignmentUkGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job/$id': {
      id: '/job/$id'
      path: '/job/$id'
      fullPath: '/job/$id'
      preLoaderRoute: typeof JobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$code': {
      id: '/p/$code'
      path: '/p/$code'
      fullPath: '/p/$code'
      preLoaderRoute: typeof PCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technician/': {
      id: '/technician/'
      path: '/technician'
      fullPath: '/technician/'
      preLoaderRoute: typeof TechnicianIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technician/login': {
      id: '/technician/login'
      path: '/technician/login'
      fullPath: '/technician/login'
      preLoaderRoute: typeof TechnicianLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technician/onboarding': {
      id: '/technician/onboarding'
      path: '/technician/onboarding'
      fullPath: '/technician/onboarding'
      preLoaderRoute: typeof TechnicianOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/activity': {
      id: '/admin/dashboard/activity'
      path: '/activity'
      fullPath: '/admin/dashboard/activity'
      preLoaderRoute: typeof AdminDashboardActivityRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/admin-ai-instructions': {
      id: '/admin/dashboard/admin-ai-instructions'
      path: '/admin-ai-instructions'
      fullPath: '/admin/dashboard/admin-ai-instructions'
      preLoaderRoute: typeof AdminDashboardAdminAiInstructionsRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/ai-settings': {
      id: '/admin/dashboard/ai-settings'
      path: '/ai-settings'
      fullPath: '/admin/dashboard/ai-settings'
      preLoaderRoute: typeof AdminDashboardAiSettingsRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/command': {
      id: '/admin/dashboard/command'
      path: '/command'
      fullPath: '/admin/dashboard/command'
      preLoaderRoute: typeof AdminDashboardCommandRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/jobs': {
      id: '/admin/dashboard/jobs'
      path: '/jobs'
      fullPath: '/admin/dashboard/jobs'
      preLoaderRoute: typeof AdminDashboardJobsRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/payments': {
      id: '/admin/dashboard/payments'
      path: '/payments'
      fullPath: '/admin/dashboard/payments'
      preLoaderRoute: typeof AdminDashboardPaymentsRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/quotes': {
      id: '/admin/dashboard/quotes'
      path: '/quotes'
      fullPath: '/admin/dashboard/quotes'
      preLoaderRoute: typeof AdminDashboardQuotesRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/reports': {
      id: '/admin/dashboard/reports'
      path: '/reports'
      fullPath: '/admin/dashboard/reports'
      preLoaderRoute: typeof AdminDashboardReportsRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/settings': {
      id: '/admin/dashboard/settings'
      path: '/settings'
      fullPath: '/admin/dashboard/settings'
      preLoaderRoute: typeof AdminDashboardSettingsRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/technician-ai-instructions': {
      id: '/admin/dashboard/technician-ai-instructions'
      path: '/technician-ai-instructions'
      fullPath: '/admin/dashboard/technician-ai-instructions'
      preLoaderRoute: typeof AdminDashboardTechnicianAiInstructionsRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/technicians': {
      id: '/admin/dashboard/technicians'
      path: '/technicians'
      fullPath: '/admin/dashboard/technicians'
      preLoaderRoute: typeof AdminDashboardTechniciansRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/services/$service/': {
      id: '/services/$service/'
      path: '/services/$service'
      fullPath: '/services/$service/'
      preLoaderRoute: typeof ServicesServiceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$service/$city': {
      id: '/services/$service/$city'
      path: '/services/$service/$city'
      fullPath: '/services/$service/$city'
      preLoaderRoute: typeof ServicesServiceCityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminDashboardRouteChildren {
  AdminDashboardActivityRoute: typeof AdminDashboardActivityRoute
  AdminDashboardAdminAiInstructionsRoute: typeof AdminDashboardAdminAiInstructionsRoute
  AdminDashboardAiSettingsRoute: typeof AdminDashboardAiSettingsRoute
  AdminDashboardCommandRoute: typeof AdminDashboardCommandRoute
  AdminDashboardJobsRoute: typeof AdminDashboardJobsRoute
  AdminDashboardPaymentsRoute: typeof AdminDashboardPaymentsRoute
  AdminDashboardQuotesRoute: typeof AdminDashboardQuotesRoute
  AdminDashboardReportsRoute: typeof AdminDashboardReportsRoute
  AdminDashboardSettingsRoute: typeof AdminDashboardSettingsRoute
  AdminDashboardTechnicianAiInstructionsRoute: typeof AdminDashboardTechnicianAiInstructionsRoute
  AdminDashboardTechniciansRoute: typeof AdminDashboardTechniciansRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
}

const AdminDashboardRouteChildren: AdminDashboardRouteChildren = {
  AdminDashboardActivityRoute: AdminDashboardActivityRoute,
  AdminDashboardAdminAiInstructionsRoute:
    AdminDashboardAdminAiInstructionsRoute,
  AdminDashboardAiSettingsRoute: AdminDashboardAiSettingsRoute,
  AdminDashboardCommandRoute: AdminDashboardCommandRoute,
  AdminDashboardJobsRoute: AdminDashboardJobsRoute,
  AdminDashboardPaymentsRoute: AdminDashboardPaymentsRoute,
  AdminDashboardQuotesRoute: AdminDashboardQuotesRoute,
  AdminDashboardReportsRoute: AdminDashboardReportsRoute,
  AdminDashboardSettingsRoute: AdminDashboardSettingsRoute,
  AdminDashboardTechnicianAiInstructionsRoute:
    AdminDashboardTechnicianAiInstructionsRoute,
  AdminDashboardTechniciansRoute: AdminDashboardTechniciansRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
}

const AdminDashboardRouteWithChildren = AdminDashboardRoute._addFileChildren(
  AdminDashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfirmedRoute: ConfirmedRoute,
  ConsoleRoute: ConsoleRoute,
  Dash2Route: Dash2Route,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AdminDashboardRoute: AdminDashboardRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AreasSlugRoute: AreasSlugRoute,
  Blog24HourPunctureRepairLondonRoute: Blog24HourPunctureRepairLondonRoute,
  BlogAllSeasonVsWinterTyresUkRoute: BlogAllSeasonVsWinterTyresUkRoute,
  BlogBudgetVsPremiumTyresUkRoute: BlogBudgetVsPremiumTyresUkRoute,
  BlogCanAPunctureBeRepairedUkRoute: BlogCanAPunctureBeRepairedUkRoute,
  BlogCanIDriveOnAFlatTyreUkRoute: BlogCanIDriveOnAFlatTyreUkRoute,
  BlogCrackedAlloyFromPotholeRoute: BlogCrackedAlloyFromPotholeRoute,
  BlogEmergencyPunctureRepairLondonRoute:
    BlogEmergencyPunctureRepairLondonRoute,
  BlogFlatTyreLondonRoute: BlogFlatTyreLondonRoute,
  BlogLockingWheelNutLostUkRoute: BlogLockingWheelNutLostUkRoute,
  BlogMobilePunctureRepairLondonRoute: BlogMobilePunctureRepairLondonRoute,
  BlogMobileTyreFitterM25Route: BlogMobileTyreFitterM25Route,
  BlogMobileTyreFitterVsGarageRoute: BlogMobileTyreFitterVsGarageRoute,
  BlogMobileTyreFittingBirminghamRoute: BlogMobileTyreFittingBirminghamRoute,
  BlogMobileTyreFittingLondonRoute: BlogMobileTyreFittingLondonRoute,
  BlogMobileTyreFittingManchesterRoute: BlogMobileTyreFittingManchesterRoute,
  BlogNailInTyreWhatToDoRoute: BlogNailInTyreWhatToDoRoute,
  BlogPotholeDamageClaimUkRoute: BlogPotholeDamageClaimUkRoute,
  BlogPunctureRepairCentralLondonRoute: BlogPunctureRepairCentralLondonRoute,
  BlogPunctureRepairCostUkRoute: BlogPunctureRepairCostUkRoute,
  BlogPunctureRepairVsNewTyreRoute: BlogPunctureRepairVsNewTyreRoute,
  BlogRoadsidePunctureRepairLondonRoute: BlogRoadsidePunctureRepairLondonRoute,
  BlogRunFlatPunctureRepairLondonRoute: BlogRunFlatPunctureRepairLondonRoute,
  BlogRunFlatTyresUkGuideRoute: BlogRunFlatTyresUkGuideRoute,
  BlogRunFlatVsStandardTyresRoute: BlogRunFlatVsStandardTyresRoute,
  BlogSameDayPunctureRepairLondonRoute: BlogSameDayPunctureRepairLondonRoute,
  BlogSlowPunctureUkGuideRoute: BlogSlowPunctureUkGuideRoute,
  BlogTpmsWarningLightRoute: BlogTpmsWarningLightRoute,
  BlogTwentyFourHourTyreChangeLondonRoute:
    BlogTwentyFourHourTyreChangeLondonRoute,
  BlogTyreAgeWhenToReplaceRoute: BlogTyreAgeWhenToReplaceRoute,
  BlogTyreBlowoutOnMotorwayWhatToDoRoute:
    BlogTyreBlowoutOnMotorwayWhatToDoRoute,
  BlogTyreBulgeSidewallDangerRoute: BlogTyreBulgeSidewallDangerRoute,
  BlogTyrePressureGuideUkRoute: BlogTyrePressureGuideUkRoute,
  BlogTyreSidewallDamageGuideRoute: BlogTyreSidewallDamageGuideRoute,
  BlogUkTyreLegalTreadDepthRoute: BlogUkTyreLegalTreadDepthRoute,
  BlogWheelAlignmentUkGuideRoute: BlogWheelAlignmentUkGuideRoute,
  JobIdRoute: JobIdRoute,
  PCodeRoute: PCodeRoute,
  TechnicianLoginRoute: TechnicianLoginRoute,
  TechnicianOnboardingRoute: TechnicianOnboardingRoute,
  AdminIndexRoute: AdminIndexRoute,
  AreasIndexRoute: AreasIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  TechnicianIndexRoute: TechnicianIndexRoute,
  ServicesServiceCityRoute: ServicesServiceCityRoute,
  ServicesServiceIndexRoute: ServicesServiceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
